# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sinatra", "~> 2.2.0"
gem 'sinatra-cross_origin', "~> 0.4.0"
gem "tanker-identity", path: "../../"
gem "thin", "~> 1.8.1"
