name: Tests
on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3', '3.4']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: sudo apt install -y libsodium23
      - name: Install bundler
        run: gem install bundler
      - name: Install dev dependencies
        run: bundle install
      - name: Check vulnerabilities
        run: bundle exec bundle-audit check --update
      - name: Run tests
        run: bundle exec rspec
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install and configure poetry
        run: |
          python -m pip install poetry
          python -m poetry config virtualenvs.create false
      - name: Install python packages
        run: python -m poetry install
      - name: Run python linters
        run: |
          python -m poetry run black --check --diff run-ci.py
          python -m poetry run flake8 run-ci.py
          python -m poetry run isort --check --diff run-ci.py
          python -m poetry run mypy run-ci.py
