name: Tests
on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.5, 2.6]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: sudo apt install -y libsodium23
      - name: Install bundler
        run: gem install bundler
      - name: Install gem
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
