name: Deploy
on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1 
        with: 
          python-version: '3.10'
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install and configure poetry
        run: python -m pip install poetry
      - name: Install python packages
        run: python -m poetry install --no-dev
      - name: Configure rubygems permissions
        run: mkdir -p "${HOME}/.gem" && echo ':rubygems_api_key:'" \"${RUBYGEMS_API_KEY}\"" > "${HOME}/.gem/credentials" && chmod 0600 "${HOME}/.gem/credentials" 
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      - name: Deploy
        run: python -m poetry run python run-ci.py deploy --version "${GITHUB_REF#refs/tags/}"